mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('poll.urls'))
]

poll/urls.py
from .views import detail,results,vote,index
from django.urls import path


app_name = 'poll'
urlpatterns = [
    path('', index, name='index'),
    path('poll/<int:question_id>',detail,name="detail"),
    path('result/<int:question_id>',results,name="result"),
    path('vote/<int:question_id>',vote,name="vote"),
    
]

poll/models.py
from django.db import models

# Create your models here.
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_publish_recently(self):
        return True

    def __str__(self):
        return self.question_text 


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,Http404, HttpResponseRedirect
from .models import Question
from django.template import loader
from django.urls import reverse

# Create your views here.
def index(request):
    output = Question.objects.order_by('pub_date')
    # output = ', '.join([q.question_text for q in output])
    template = loader.get_template('index.html')
    context = {
        'latest_question_list':output,
    }
    return render(request,'index.html',context)



def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except:
    #     raise http404("question not found")
    


    #this is the eqivalent of above

    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question':question
    }

    return render(request,'detail.html',context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'results.html', {'question': question})

    

def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {
            'question': question,
            'error_message': "You didn't select a choice.",
        }
        return render(request,'detail.html',context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:result', args=(question.id,)))
    

poll/templates/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'poll:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name='choice' id="choice{{forloop.counter}}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>

    {% endfor %}
    <input type="submit" value="vote">
</form>
<!-- <ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

poll/templates/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% if latest_question_list %}
    <ul>
        {% for p in latest_question_list %}
        <li><a href="{% url 'poll:detail' p.id %}">{{ p.question_text }} bhuban ghimire</a></li>
        {% endfor %}
    </ul>
{% endif %}

poll/templates/results.html
<!-- polls/templates/polls/results.html¶ -->
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a>